import type {Metadata} from 'next';
import {Inter} from 'next/font/google';
import Head from 'next/head';
import './global.css';
import Header from '../components/header/Header';
import {getServerSession} from "next-auth";
import SessionProvider from "@/components/sessionProvider/SessionProvider";
import React from "react";


const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
                                             children,
                                         }: {
    children: React.ReactNode;
}) {

    const session = await getServerSession();

    return (
        <html lang="en">
        <Head>
            <link
                rel="preconnect"
                href="https://fonts.googleapis.com"
            />
            <link
                rel="preconnect"
                href="https://fonts.gstatic.com"
            />
            <link
                href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@600&display=swap"
                rel="stylesheet"/>
        </Head>
        <body className={inter.className}>
        <SessionProvider session={session}>
            <Header/>
            {children}
        </SessionProvider>
        </body>
        </html>
    );
}
